//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstHomeBrew.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductLinks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductLinks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirstHomeBrew.Content.Resources.ProductLinks", typeof(ProductLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00A6TRKO4/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00A6TRKO4&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=ZJR3NPR44HVFIDPK.
        /// </summary>
        public static string Airlock {
            get {
                return ResourceManager.GetString("Airlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00DDFGRVU/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00DDFGRVU&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=AY43AC37KNMVBH2D.
        /// </summary>
        public static string BottleDryingRack {
            get {
                return ResourceManager.GetString("BottleDryingRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00838VPHS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00838VPHS&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=VWKVPENZKH4SXYSF.
        /// </summary>
        public static string BottleFiller {
            get {
                return ResourceManager.GetString("BottleFiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B000E62H8I/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B000E62H8I&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=FPTBVXJINKKGMXZM.
        /// </summary>
        public static string BottlingBucket {
            get {
                return ResourceManager.GetString("BottlingBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B005I5FO8K/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B005I5FO8K&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=HJW5CVMNKF22B6B3.
        /// </summary>
        public static string BrewPot {
            get {
                return ResourceManager.GetString("BrewPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00W3PVGR6/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00W3PVGR6&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=FTS6ZA3JM263IGNP.
        /// </summary>
        public static string Burner {
            get {
                return ResourceManager.GetString("Burner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B001D6KGTK/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B001D6KGTK&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=E2EX4MQV2NYQSD5W.
        /// </summary>
        public static string Capper {
            get {
                return ResourceManager.GetString("Capper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00W3PY7IG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00W3PY7IG&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=JVWTVBIURO5XIYOG.
        /// </summary>
        public static string Carboy {
            get {
                return ResourceManager.GetString("Carboy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B01B44ISWC/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B01B44ISWC&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=ZGD2HQI6UHIJ6FJN.
        /// </summary>
        public static string FoodThermometer {
            get {
                return ResourceManager.GetString("FoodThermometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B008S0KNZG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B008S0KNZG&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=SDBXVHKKQB272IWS.
        /// </summary>
        public static string Hydrometer {
            get {
                return ResourceManager.GetString("Hydrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00AC73NJG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00AC73NJG&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=OBEEWYN3GCAOUCTA.
        /// </summary>
        public static string IngredientsKit {
            get {
                return ResourceManager.GetString("IngredientsKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B005GI8UPI/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B005GI8UPI&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=XOJC3KVZ7XZDRSFP.
        /// </summary>
        public static string OxiClean {
            get {
                return ResourceManager.GetString("OxiClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B000E62TCC/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B000E62TCC&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=FYCNOQCS67VMCRVC.
        /// </summary>
        public static string PlasticTubing {
            get {
                return ResourceManager.GetString("PlasticTubing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B000FOV0MS/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B000FOV0MS&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=LKA6B4KPQF7BB4GR.
        /// </summary>
        public static string SiliconeTubing {
            get {
                return ResourceManager.GetString("SiliconeTubing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B0064ODELI/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B0064ODELI&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=H7Z3P76KEW3PLQOC.
        /// </summary>
        public static string Siphon {
            get {
                return ResourceManager.GetString("Siphon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B0064O7YFA/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B0064O7YFA&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=5ORNDV6YOVV2U4OJ.
        /// </summary>
        public static string StarSan {
            get {
                return ResourceManager.GetString("StarSan", resourceCulture);
            }
        }
    }
}
