//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstHomeBrew.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductLinks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductLinks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirstHomeBrew.Content.Resources.ProductLinks", typeof(ProductLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00A6TRKO4/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00A6TRKO4&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=ZJR3NPR44HVFIDPK.
        /// </summary>
        public static string Airlock {
            get {
                return ResourceManager.GetString("Airlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  href=&quot;http://www.amazon.com/gp/product/B00DDFGRVU/ref=as_li_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00DDFGRVU&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=MXR45EHUIC5OCPWC&quot;&gt;&lt;img border=&quot;0&quot; src=&quot;http://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&amp;ASIN=B00DDFGRVU&amp;Format=_SL250_&amp;ID=AsinImage&amp;MarketPlace=US&amp;ServiceVersion=20070822&amp;WS=1&amp;tag=firhombre-20&quot; &gt;&lt;/a&gt;&lt;img src=&quot;http://ir-na.amazon-adsystem.com/e/ir?t=firhombre-20&amp;l=as2&amp;o=1&amp;a=B00DDFGRVU&quot; width=&quot;1&quot; height=&quot;1&quot; border=&quot;0&quot; alt=&quot;&quot; style=&quot;border:none [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BottleDryingRack {
            get {
                return ResourceManager.GetString("BottleDryingRack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  href=&quot;http://www.amazon.com/gp/product/B00838VPHS/ref=as_li_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00838VPHS&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=AVFUDUSBMXBG7KZG&quot;&gt;&lt;img border=&quot;0&quot; src=&quot;http://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&amp;ASIN=B00838VPHS&amp;Format=_SL250_&amp;ID=AsinImage&amp;MarketPlace=US&amp;ServiceVersion=20070822&amp;WS=1&amp;tag=firhombre-20&quot; &gt;&lt;/a&gt;&lt;img src=&quot;http://ir-na.amazon-adsystem.com/e/ir?t=firhombre-20&amp;l=as2&amp;o=1&amp;a=B00838VPHS&quot; width=&quot;1&quot; height=&quot;1&quot; border=&quot;0&quot; alt=&quot;&quot; style=&quot;border:none [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BottleFiller {
            get {
                return ResourceManager.GetString("BottleFiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B000E62H8I/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B000E62H8I&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=FPTBVXJINKKGMXZM.
        /// </summary>
        public static string BottlingBucket {
            get {
                return ResourceManager.GetString("BottlingBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B005I5FO8K/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B005I5FO8K&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=HJW5CVMNKF22B6B3.
        /// </summary>
        public static string BrewPot {
            get {
                return ResourceManager.GetString("BrewPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00W3PVGR6/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00W3PVGR6&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=FTS6ZA3JM263IGNP.
        /// </summary>
        public static string Burner {
            get {
                return ResourceManager.GetString("Burner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B001D6KGTK/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B001D6KGTK&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=E2EX4MQV2NYQSD5W.
        /// </summary>
        public static string Capper {
            get {
                return ResourceManager.GetString("Capper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B00W3PY7IG/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B00W3PY7IG&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=JVWTVBIURO5XIYOG.
        /// </summary>
        public static string Carboy {
            get {
                return ResourceManager.GetString("Carboy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a  href=&quot;http://www.amazon.com/gp/product/B008S0KNZG/ref=as_li_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B008S0KNZG&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=S3Y4NA65KTKKEOVI&quot;&gt;&lt;img border=&quot;0&quot; src=&quot;http://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&amp;ASIN=B008S0KNZG&amp;Format=_SL250_&amp;ID=AsinImage&amp;MarketPlace=US&amp;ServiceVersion=20070822&amp;WS=1&amp;tag=firhombre-20&quot; &gt;&lt;/a&gt;&lt;img src=&quot;http://ir-na.amazon-adsystem.com/e/ir?t=firhombre-20&amp;l=as2&amp;o=1&amp;a=B008S0KNZG&quot; width=&quot;1&quot; height=&quot;1&quot; border=&quot;0&quot; alt=&quot;&quot; style=&quot;border:none [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Hydrometer {
            get {
                return ResourceManager.GetString("Hydrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.amazon.com/gp/product/B0064ODELI/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=B0064ODELI&amp;linkCode=as2&amp;tag=firhombre-20&amp;linkId=H7Z3P76KEW3PLQOC.
        /// </summary>
        public static string Siphon {
            get {
                return ResourceManager.GetString("Siphon", resourceCulture);
            }
        }
    }
}
